;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        ))

(setq mc/cmds-to-run-once
      '(
        electrify-return-if-match
        helm-M-x
        hydra-multiple-cursors/body
        hydra-multiple-cursors/mc-hide-unmatched-lines-mode
        hydra-multiple-cursors/mc/mark-all-like-this
        hydra-multiple-cursors/mc/mark-all-words-like-this
        hydra-multiple-cursors/mc/mark-next-like-this
        hydra-multiple-cursors/mc/mark-next-word-like-this
        hydra-multiple-cursors/mc/mark-previous-word-like-this
        hydra-multiple-cursors/mc/unmark-next-like-this
        hydra-multiple-cursors/mc/unmark-previous-like-this
        hydra-multiple-cursors/nil
        kmacro-end-macro
        ))
