;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        go-mode-insert-and-indent
        kill-region
        ))

(setq mc/cmds-to-run-once
      '(
        beginning-of-buffer
        electrify-return-if-match
        helm-M-x
        hydra-multiple-cursors/body
        hydra-multiple-cursors/mc-hide-unmatched-lines-mode
        hydra-multiple-cursors/mc/mark-all-like-this
        hydra-multiple-cursors/mc/mark-all-words-like-this
        hydra-multiple-cursors/mc/mark-next-like-this
        hydra-multiple-cursors/mc/mark-next-word-like-this
        hydra-multiple-cursors/mc/mark-previous-word-like-this
        hydra-multiple-cursors/mc/unmark-next-like-this
        hydra-multiple-cursors/mc/unmark-previous-like-this
        hydra-multiple-cursors/nil
        kmacro-end-macro
        multiple-cursors-hydra/mc-hide-unmatched-lines-mode
        multiple-cursors-hydra/mc/edit-lines-and-exit
        multiple-cursors-hydra/mc/mark-all-in-region-regexp-and-exit
        multiple-cursors-hydra/mc/mark-all-like-this-and-exit
        multiple-cursors-hydra/mc/mark-all-words-like-this-and-exit
        multiple-cursors-hydra/mc/mark-next-like-this
        multiple-cursors-hydra/mc/mark-next-word-like-this
        multiple-cursors-hydra/mc/mark-previous-like-this
        multiple-cursors-hydra/mc/mark-previous-word-like-this
        multiple-cursors-hydra/mc/skip-to-next-like-this
        multiple-cursors-hydra/mc/skip-to-previous-like-this
        multiple-cursors-hydra/mc/unmark-next-like-this
        multiple-cursors-hydra/nil
        save-buffers-kill-terminal
        ))
